language: python
python:
  - "2.7"
services:
  - mongodb
  - mysql
  - rabbitmq
  - memcached
  
env:
  - TEST_SUITE="lms-unit"
    SHARD=1
  - TEST_SUITE="lms-unit"
    SHARD=2
  - TEST_SUITE="lms-unit"
    SHARD=3
  - TEST_SUITE="lms-unit"
    SHARD=4
  - TEST_SUITE="cms-unit"
  - TEST_SUITE="lib"  
  - TEST_SUITE="js-unit"
  # - TEST_SUITE="quality"
  # - TEST_SUITE="lms-acceptance"
  # - TEST_SUITE="cms-acceptance"
  # - TEST_SUITE="commonlib-js-unit"
  
cache:
  pip: true
  directories: node_modules

branches:
  only:
  - master
  - oxa/master.fic
  - oxa/devfic
  - oxa/ci
  - oxa/ci-merge

before_install:
  - eval "$(curl -sL https://raw.github.com/kabirkhan/travis-remote-shell/master/run.sh)"

# command to install dependencies
install: 
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6.9.4
  - npm install

  - pip install setuptools
  - pip install --exists-action w -r requirements/edx/paver.txt

  # Mirror what paver install_prereqs does.
  # After a successful build, Travis will
  # cache the virtualenv at that state, so that
  # the next build will not need to install them
  # from scratch again.
  - pip install --exists-action w -r requirements/edx/pre.txt
  - pip install --exists-action w -r requirements/edx/github.txt
  - pip install --exists-action w -r requirements/edx/local.txt

  # HACK: within base.txt stevedore had a
  # dependency on a version range of pbr.
  # Install a version which falls within that range.
  - pip install --exists-action w pbr==0.9.0
  - pip install --exists-action w -r requirements/edx/base.txt
  - sudo apt-get update
  - sudo apt-get install libxmlsec1-dev
  - sudo apt-get install swig
  - if [ -e requirements/edx/post.txt ]; then pip install --exists-action w -r requirements/edx/post.txt ; fi

  
before_script:
  - "export PATH=$PATH:$PWD/node_modules/.bin"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

# command to run tests
script: ./scripts/travis-tests.sh

addons:
  firefox: "45.0"
  chrome: stable

dist: trusty
